// values
var mOne = -1
var rowSpacing = 5
var appWidth = 640
var appHeight = 480
var tabViewMargin = 10
var accordionWidth = 100
var accordionHeight = 50

// fonts
var fontVazir = "qrc:/fonts/Vazir.ttf"
var fontAdele = "qrc:/fonts/Adele.ttf"
var fontShabnam = "qrc:/fonts/Shabnam.ttf"
var fontXmYekan = "qrc:/fonts/XmYekan.ttf"
var fontAwesome = "qrc:/fonts/FontAwesome.ttf"
var fontRadioSpace = "qrc:/fonts/RadioSpace.ttf"
var fontCaviarDreams = "qrc:/fonts/CaviarDreams.ttf"

// URLs
var portsLink = "qrc:/pages/ports/ports.qml"
var disksLink = "qrc:/pages/disks/disks.qml"
var pacmanLink = "qrc:/pages/pacman/pacman.qml"
var pacmanPackagesLink = "qrc:/pages/pacman/PacmanPackages.qml"
var settingsLink = "qrc:/pages/settings/settings.qml"
var servicesLink = "qrc:/pages/services/services.qml"
var dashBoardLink = "qrc:/pages/dashBoard/DashBoard.qml"
var histogramLink = "qrc:/pages/histogram/histogram.qml"
var processesLink = "qrc:/pages/processes/processes.qml"
var environmentsLink = "qrc:/pages/environments/environments.qml"
var subTitleFixerLink = "qrc:/pages/subtitleFixer/subtitleFixer.qml"
var systemdAnalyzeLink = "qrc:/pages/systemdAnalyze/systemdAnalyze.qml"
var DesktopEntryCreatorLink = "qrc:/pages/desktopEntryCreator/desktopEntryCreator.qml"

// colors
var transparent = "transparent"
var accordionBackGroundColor = "#424242"
var accordionItemBackGroundColor = "#616161" //"#1B252f"
var appColor = "white" //"#37474F"//"#546E7A"

// labels
var arch = "Arch"
var help = "Help"
var save = "Save"
var quit = "Quit"
var info = "Info"
var edit = "Edit"
var Disks = "Disks"
var pacman = "Pacman"
var packages = "Packages"
var memory = "Memory"
var tvdoon = "TvDoon"
var Utility = "Utility"
var gnulium = "Gnulium"
var appName = "Gnulium"
var scripts = "Scripts"
var preview = "Preview"
var referesh = "Refresh"
var aboutQT = "About Qt"
var hardware = "Hardware"
var settings = "Settings"
var defaults = "Defaults"
var Services = "Services"
var subFixer = "Sub Fixer"
var newDE = "New .desktop"
var dashBoard = "DashBoard"
var Processes = "Processes"
var OpenPorts = "Open Ports"
var firstRole = "firstRole"
var histogram = "Histogram"
var thirdRole = "thirdRole"
var forthRole = "forthRole"
var fifthRole = "fifthRole"
var sixthRole = "sixthRole"
var secondRole = "secondRole"
var Environments = "Environments"
var aboutGnulium = "About Gnulium"
var distribiutions = "Distributions"
var SystemdAnalyze = "SystemD Analyze"
var PackageManagers = "Package Managers"
var DesktopEntryCreator = "Desktop Entry Creator"

// images
var imgFontSize = "qrc:/images/fontSize.svg"
var imgText = "qrc:/images/text.svg"
var imgPalette = "qrc:/images/palette.svg"
var imgBlockSize = "qrc:/images/block.svg"

var imgGnu = "qrc:/images/gnu.png"
var imgTux = "qrc:/images/tux.png"
var imgRam = "qrc:/images/ram.svg"
var imgMan = "qrc:/images/man.svg"
var imgBox = "qrc:/images/box.svg"
var imgKey = "qrc:/images/key.svg"
var imgAsk = "qrc:/images/ask.svg"
var imgLock = "qrc:/images/lock.svg"
var imgQT = "qrc:/images/qtLogo.png"
var imgArch = "qrc:/images/arch.svg"
var imgChip = "qrc:/images/chip.svg"
var imgBaby = "qrc:/images/baby.svg"

var imgStop = "qrc:/images/stop.svg"
var imgExec = "qrc:/images/exec.svg"
var imgName = "qrc:/images/name.svg"
var imgType = "qrc:/images/type.svg"
var imgOnion = "qrc:/images/onion.svg"
var imgSweep = "qrc:/images/sweep.svg"
var imgRadar = "qrc:/images/radar.svg"
var imgError = "qrc:/images/cancel.svg"
var imgPower = "qrc:/images/power.svg"
var imgClose = "qrc:/images/close.svg"
var imgBorder = "qrc:/images/border.png"
var imgTvdoon = "qrc:/images/tvdoon.png"
var imgPacman = "qrc:/images/pacman.png"
var imgNvidia = "qrc:/images/nvidia.svg"
var imgGnulium = "qrc:/images/gnulium.svg"
var imgSummary = "qrc:/images/summary.svg"
var imgComment = "qrc:/images/comment.svg"
var imgCircuit = "qrc:/images/circuit.svg"
var imgService = "qrc:/images/service.svg"

var imgGnulium = "qrc:/images/gnulium.svg"
var imgSortAsc = "qrc:/images/sortAsc.svg"
var imgScripts = "qrc:/images/scripts.svg"
var imgSortDesc = "qrc:/images/sortDesc.svg"
var imgKeywords = "qrc:/images/keywords.svg"
var imgTerminal = "qrc:/images/terminal.svg"
var imgCategory = "qrc:/images/category.svg"
var imgCalendar = "qrc:/images/calendar.svg"

var imgSettings = "qrc:/images/settings.svg"
var imgGnuLinux = "qrc:/images/gnuLinux.png"
var imgHardDisk = "qrc:/images/hardDisk.svg"
var imgDataBase = "qrc:/images/database.svg"
var imgSubFixer = "qrc:/images/subFixer.svg"
var imgDashBoard = "qrc:/images/dashBoard.svg"
var imgHourGlass = "qrc:/images/hourGlass.svg"
var imgAnalytics = "qrc:/images/analytics.svg"
var imgAnalytics = "qrc:/images/analytics.svg"
var imgPacmanLogo = "qrc:/images/pacmanLogo.jpg"
var imgRepository = "qrc:/images/repository.svg"
var imgAlarmClock = "qrc:/images/alarmClock.svg"
var imgInformation = "qrc:/images/information.svg"
var imgAccumulator = "qrc:/images/accumulator.svg"
var imgInternetInfo = "qrc:/images/internetInfo.svg"
var imgDesktopEntry = "qrc:/images/desktopEntry.svg"
var imgQuestionMark = "qrc:/images/questionMark.svg"

// GIf's
var gifCirlo = "qrc:/images/gif/cirlo.gif"
var gifLoader = "qrc:/images/gif/loader.gif"
var gifPacman = "qrc:/images/gif/pacman.gif"
var gifEllipsis = "qrc:/images/gif/ellipsis.gif"
var gifPacmanGif = "qrc:/images/gif/pacmanGIF.gif"
